# Generated by Django 4.2.2 on 2023-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام شهر'),
        ),
    ]
