# Generated by Django 4.2.2 on 2023-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='واحد اندازه گیری')),
                ('english_name', models.CharField(max_length=120, unique=True, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'واحد اندازه گیری',
                'verbose_name_plural': 'واحد های اندازه گیری',
            },
        ),
    ]
