# Generated by Django 4.2.2 on 2023-06-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('name', models.CharField(max_length=120, verbose_name='نام محصول')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد محصول')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_unit', to='product.unit', verbose_name='واحد اندازه گیری')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
