# Generated by Django 4.2.2 on 2023-06-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='english_name',
        ),
    ]
