# Generated by Django 4.2.2 on 2023-06-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_alter_city_name'),
        ('product', '0003_remove_unit_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام محصول'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام انبار')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_city', to='city.city', verbose_name='شهر انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
    ]
