# Generated by Django 4.2.2 on 2023-06-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('quantity', models.PositiveIntegerField(verbose_name='موجودی این انبار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='product.product', verbose_name='محصول مورد نظر')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentory_store', to='product.store', verbose_name='انبار مورد نظر')),
            ],
        ),
    ]
