# Generated by Django 4.2.2 on 2023-06-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_inventory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='inventory_quantity',
        ),
    ]
