# Generated by Django 4.2.2 on 2023-06-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_quantity_inventory_inventory_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='inventory_quantity',
            new_name='quantity',
        ),
    ]
