# Generated by Django 4.2.2 on 2023-06-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
