# Generated by Django 4.2.2 on 2023-06-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('condition', models.CharField(choices=[('pending', 'در انتظار'), ('failed', 'رد شده'), ('confirmed', 'تایید شده')], max_length=20, verbose_name='وضعیت سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product', verbose_name='محصول')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_store', to='product.store', verbose_name='انبار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': '5 - سفارشات',
            },
        ),
    ]
